// AUTO-GENERATED icon registry — the ONLY module allowed to import from 'react-icons/*'.
// Names are family-agnostic (shape-based, 'Icon'-suffixed). Swapping an icon family
// means changing the right-hand side here; call sites never change.
import React from 'react';
import { FaUserClock } from 'react-icons/fa';
import { GiSouthKorea } from 'react-icons/gi';
import { LuFileJson } from 'react-icons/lu';
import { MdCardMembership, MdPreview, MdThumbsUpDown } from 'react-icons/md';
import { PiExam } from 'react-icons/pi';
import {
  TbActivity,
  TbAlertCircle,
  TbAlertCircleFilled,
  TbAlertOctagon,
  TbAlertTriangle,
  TbAlertTriangleFilled,
  TbAppWindowFilled,
  TbArchive,
  TbArrowBackUp,
  TbArrowDownRight,
  TbArrowForwardUp,
  TbArrowsDiagonal,
  TbArrowsLeftRight,
  TbArrowsMinimize,
  TbArrowUpRight,
  TbBeer,
  TbBell,
  TbBlockquote,
  TbBold,
  TbBolt,
  TbBoltFilled,
  TbBook,
  TbBookFilled,
  TbBug,
  TbBuildingBank,
  TbBuildingCommunity,
  TbBulb,
  TbCalendar,
  TbCash,
  TbChartBar,
  TbChartLine,
  TbChartPie,
  TbCheck,
  TbChevronDown,
  TbChevronLeft,
  TbChevronRight,
  TbChevronUp,
  TbCircleCheck,
  TbCirclePlus,
  TbClock,
  TbClockFilled,
  TbCode,
  TbCoins,
  TbCopy,
  TbCreditCard,
  TbCreditCardFilled,
  TbDeviceDesktop,
  TbDeviceFloppy,
  TbDots,
  TbDownload,
  TbExternalLink,
  TbEye,
  TbEyeOff,
  TbFile,
  TbFileCode,
  TbFileFilled,
  TbFileMusic,
  TbFileSpreadsheet,
  TbFileText,
  TbFileZip,
  TbFilter,
  TbGift,
  TbGripVertical,
  TbHeadset,
  TbHelpCircle,
  TbHierarchy3,
  TbHome,
  TbHomeFilled,
  TbInfinity,
  TbInfoCircle,
  TbItalic,
  TbKey,
  TbLanguage,
  TbLayoutDashboard,
  TbLayoutDashboardFilled,
  TbLayoutNavbar,
  TbLayoutSidebar,
  TbLayoutSidebarLeftCollapse,
  TbLink,
  TbList,
  TbListDetails,
  TbListNumbers,
  TbLock,
  TbLockCog,
  TbLockOpen,
  TbLogout,
  TbMail,
  TbMap2,
  TbMaximize,
  TbMenu2,
  TbMessageChatbotFilled,
  TbMessageDots,
  TbMessageOff,
  TbMessageReport,
  TbMicrophone,
  TbMicrophoneOff,
  TbMinus,
  TbMoon,
  TbMovie,
  TbNews,
  TbNote,
  TbNotebook,
  TbNotes,
  TbPaperclip,
  TbPhoneFilled,
  TbPhoto,
  TbPinFilled,
  TbPlayerPauseFilled,
  TbPlayerPlayFilled,
  TbPlayerStopFilled,
  TbPlus,
  TbPresentation,
  TbPrinter,
  TbReceipt,
  TbRefresh,
  TbReport,
  TbRosetteDiscountCheckFilled,
  TbRotate,
  TbRotateClockwise,
  TbScale,
  TbSchool,
  TbSearch,
  TbSend,
  TbSettings,
  TbShare,
  TbShare3,
  TbShieldCheck,
  TbSitemap,
  TbSortAscendingLetters,
  TbSortAscendingNumbers,
  TbSortDescendingLetters,
  TbSortDescendingNumbers,
  TbSourceCode,
  TbSpeakerphone,
  TbStar,
  TbStarFilled,
  TbStrikethrough,
  TbSum,
  TbSun,
  TbTable,
  TbTarget,
  TbThumbDown,
  TbThumbDownFilled,
  TbThumbUp,
  TbThumbUpFilled,
  TbTrash,
  TbUnderline,
  TbUnlink,
  TbUpload,
  TbUser,
  TbUserCheck,
  TbUserCircle,
  TbUserFilled,
  TbUserPin,
  TbUserPlus,
  TbUsers,
  TbUserShield,
  TbVolume,
  TbVolume2,
  TbVolumeOff,
  TbWorld,
  TbWorldOff,
  TbWorldSearch,
  TbX,
  TbZoomIn,
  TbZoomOut,
  TbZoomQuestion,
} from 'react-icons/tb';

import createIcon from '@/components/Icon/_utils/createIcon';

// Custom brand SVG icons
import AmountUsage from '../icons/amount-usage.svg';
import Analytics from '../icons/analytics.svg';
import Bulb from '../icons/bulb.svg';
import Chat from '../icons/chat.svg';
import Dashboard from '../icons/dashboard.svg';
import Edit from '../icons/edit.svg';
import Face from '../icons/face.svg';
import Faq from '../icons/faq.svg';
import FilledAmountUsage from '../icons/filled-amount-usage.svg';
import FilledAnalytics from '../icons/filled-analytics.svg';
import FilledBulb from '../icons/filled-bulb.svg';
import FilledChat from '../icons/filled-chat.svg';
import FilledEdit from '../icons/filled-edit.svg';
import FilledFace from '../icons/filled-face.svg';
import FilledFaq from '../icons/filled-faq.svg';
import FilledLayout from '../icons/filled-layout.svg';
import FilledMembers from '../icons/filled-members.svg';
import Language from '../icons/language.svg';
import Layout from '../icons/layout.svg';
import Members from '../icons/members.svg';
import Pending from '../icons/pending.svg';
import Receipt from '../icons/receipt.svg';
import Sparkles from '../icons/sparkles.svg';
import Store from '../icons/store.svg';
import StoreActive from '../icons/store_active.svg';
import Studio from '../icons/studio.svg';
import StudioActive from '../icons/studio_active.svg';
import VerticalEllipsis from '../icons/vertical-ellipsis.svg';
import Window from '../icons/window.svg';

// Family-agnostic registry (canonical names)
const registry = {
  ActivityIcon: TbActivity,
  AlertCircleFilledIcon: TbAlertCircleFilled,
  AlertCircleIcon: TbAlertCircle,
  AlertOctagonIcon: TbAlertOctagon,
  AlertTriangleIcon: TbAlertTriangle,
  AmountUsageIcon: AmountUsage,
  AnalyticsIcon: Analytics,
  AnnouncementIcon: TbMessageReport,
  AppWindowFilledIcon: TbAppWindowFilled,
  ArchiveIcon: TbArchive,
  ArrowBackUpIcon: TbArrowBackUp,
  ArrowDownRightIcon: TbArrowDownRight,
  ArrowForwardUpIcon: TbArrowForwardUp,
  ArrowsLeftRightIcon: TbArrowsLeftRight,
  ArrowsMinimizeIcon: TbArrowsMinimize,
  ArrowUpRightIcon: TbArrowUpRight,
  BeerIcon: TbBeer,
  BellIcon: TbBell,
  BlockquoteIcon: TbBlockquote,
  BoldIcon: TbBold,
  BoltFilledIcon: TbBoltFilled,
  BoltIcon: TbBolt,
  BookFilledIcon: TbBookFilled,
  BookIcon: TbBook,
  BugIcon: TbBug,
  BuildingBankIcon: TbBuildingBank,
  BuildingUserIcon: TbBuildingCommunity,
  BulbIcon: Bulb,
  CalendarIcon: TbCalendar,
  CardMembershipIcon: MdCardMembership,
  CashIcon: TbCash,
  ChartBarIcon: TbChartBar,
  ChartLineIcon: TbChartLine,
  ChartPieIcon: TbChartPie,
  ChatIcon: Chat,
  CheckIcon: TbCheck,
  ChevronDownIcon: TbChevronDown,
  ChevronLeftIcon: TbChevronLeft,
  ChevronRightIcon: TbChevronRight,
  ChevronUpIcon: TbChevronUp,
  CircleCheckIcon: TbCircleCheck,
  CirclePlusIcon: TbCirclePlus,
  ClockFilledIcon: TbClockFilled,
  ClockIcon: TbClock,
  CloseIcon: TbX,
  CodeIcon: TbCode,
  CoinsIcon: TbCoins,
  CopyIcon: TbCopy,
  CreditCardFilledIcon: TbCreditCardFilled,
  CreditCardIcon: TbCreditCard,
  DashboardIcon: Dashboard,
  DetailIcon: TbListDetails,
  DotsHorizontalIcon: TbDots,
  DownloadIcon: TbDownload,
  EditIcon: Edit,
  ExamIcon: PiExam,
  ExpandAltIcon: TbArrowsDiagonal,
  ExternalLinkIcon: TbExternalLink,
  EyeIcon: TbEye,
  EyeOffIcon: TbEyeOff,
  FaceIcon: Face,
  FaqIcon: Faq,
  FileCodeIcon: TbFileCode,
  FileFilledIcon: TbFileFilled,
  FileIcon: TbFile,
  FileJsonIcon: LuFileJson,
  FileMusicIcon: TbFileMusic,
  FileSpreadsheetIcon: TbFileSpreadsheet,
  FileTextIcon: TbFileText,
  FileVideoIcon: TbMovie,
  FileZipIcon: TbFileZip,
  FilledAmountUsageIcon: FilledAmountUsage,
  FilledAnalyticsIcon: FilledAnalytics,
  FilledBulbIcon: FilledBulb,
  FilledChatIcon: FilledChat,
  FilledEditIcon: FilledEdit,
  FilledFaceIcon: FilledFace,
  FilledFaqIcon: FilledFaq,
  FilledLayoutIcon: FilledLayout,
  FilledMembersIcon: FilledMembers,
  FilterIcon: TbFilter,
  GiftIcon: TbGift,
  GripVerticalIcon: TbGripVertical,
  HeadsetIcon: TbHeadset,
  HelpCircleIcon: TbHelpCircle,
  Hierarchy3Icon: TbHierarchy3,
  HomeFilledIcon: TbHomeFilled,
  HomeIcon: TbHome,
  InfinityIcon: TbInfinity,
  InfoCircleIcon: TbInfoCircle,
  ItalicIcon: TbItalic,
  KeyIcon: TbKey,
  LanguageIcon: Language,
  LayoutDashboardFilledIcon: TbLayoutDashboardFilled,
  LayoutDashboardIcon: TbLayoutDashboard,
  LayoutIcon: Layout,
  LayoutNavbarIcon: TbLayoutNavbar,
  LightbulbIcon: TbBulb,
  LinkIcon: TbLink,
  ListIcon: TbList,
  ListNumbersIcon: TbListNumbers,
  LockCogIcon: TbLockCog,
  LockIcon: TbLock,
  LockOpenIcon: TbLockOpen,
  LogoutIcon: TbLogout,
  MailIcon: TbMail,
  Map2Icon: TbMap2,
  MaximizeIcon: TbMaximize,
  MembersIcon: Members,
  MenuIcon: TbMenu2,
  MessageChatbotFilledIcon: TbMessageChatbotFilled,
  MessageDotsIcon: TbMessageDots,
  MessageOffIcon: TbMessageOff,
  MicrophoneIcon: TbMicrophone,
  MicrophoneOffIcon: TbMicrophoneOff,
  MinusIcon: TbMinus,
  MonitorIcon: TbDeviceDesktop,
  MoonIcon: TbMoon,
  NewsIcon: TbNews,
  NotebookIcon: TbNotebook,
  NotesIcon: TbNotes,
  PaperclipIcon: TbPaperclip,
  PauseFilledIcon: TbPlayerPauseFilled,
  PendingIcon: Pending,
  PhoneFilledIcon: TbPhoneFilled,
  PhotoIcon: TbPhoto,
  PinFilledIcon: TbPinFilled,
  PlayFilledIcon: TbPlayerPlayFilled,
  PlusIcon: TbPlus,
  PresentationIcon: TbPresentation,
  PreviewIcon: MdPreview,
  PrinterIcon: TbPrinter,
  ReceiptIcon: Receipt,
  ReceiptTextIcon: TbReceipt,
  RefreshIcon: TbRefresh,
  ReportIcon: TbReport,
  RotateClockwiseIcon: TbRotateClockwise,
  RotateIcon: TbRotate,
  SaveIcon: TbDeviceFloppy,
  ScaleIcon: TbScale,
  SchoolIcon: TbSchool,
  SearchIcon: TbSearch,
  SendIcon: TbSend,
  SettingsIcon: TbSettings,
  Share3Icon: TbShare3,
  ShareIcon: TbShare,
  ShieldCheckIcon: TbShieldCheck,
  SidebarCollapseIcon: TbLayoutSidebarLeftCollapse,
  SidebarIcon: TbLayoutSidebar,
  SitemapIcon: TbSitemap,
  SortAscendingLettersIcon: TbSortAscendingLetters,
  SortAscendingNumbersIcon: TbSortAscendingNumbers,
  SortDescendingLettersIcon: TbSortDescendingLetters,
  SortDescendingNumbersIcon: TbSortDescendingNumbers,
  SourceCodeIcon: TbSourceCode,
  SouthKoreaIcon: GiSouthKorea,
  SparklesIcon: Sparkles,
  SpeakerphoneIcon: TbSpeakerphone,
  StarFilledIcon: TbStarFilled,
  StarIcon: TbStar,
  StickyNoteIcon: TbNote,
  StopFilledIcon: TbPlayerStopFilled,
  StoreActiveIcon: StoreActive,
  StoreIcon: Store,
  StrikethroughIcon: TbStrikethrough,
  StudioActiveIcon: StudioActive,
  StudioIcon: Studio,
  SumIcon: TbSum,
  SunIcon: TbSun,
  TableIcon: TbTable,
  TargetIcon: TbTarget,
  ThumbDownFilledIcon: TbThumbDownFilled,
  ThumbDownIcon: TbThumbDown,
  ThumbsUpDownIcon: MdThumbsUpDown,
  ThumbUpFilledIcon: TbThumbUpFilled,
  ThumbUpIcon: TbThumbUp,
  TranslateIcon: TbLanguage,
  TrashIcon: TbTrash,
  UnderlineIcon: TbUnderline,
  UnlinkIcon: TbUnlink,
  UploadIcon: TbUpload,
  UserCheckIcon: TbUserCheck,
  UserCircleIcon: TbUserCircle,
  UserClockIcon: FaUserClock,
  UserFilledIcon: TbUserFilled,
  UserIcon: TbUser,
  UserPinIcon: TbUserPin,
  UserPlusIcon: TbUserPlus,
  UserShieldIcon: TbUserShield,
  UsersIcon: TbUsers,
  VerifiedIcon: TbRosetteDiscountCheckFilled,
  VerticalEllipsisIcon: VerticalEllipsis,
  VolumeHighIcon: TbVolume,
  VolumeLowIcon: TbVolume2,
  VolumeMuteIcon: TbVolumeOff,
  WarningIcon: TbAlertTriangleFilled,
  WindowIcon: Window,
  WorldIcon: TbWorld,
  WorldOffIcon: TbWorldOff,
  WorldSearchIcon: TbWorldSearch,
  ZoomInIcon: TbZoomIn,
  ZoomOutIcon: TbZoomOut,
  ZoomQuestionIcon: TbZoomQuestion,
};

// Backward-compat aliases — old family-prefixed / bare names kept working during migration.
// TODO(icon-migration Phase 4): remove once no call site imports these.
const legacyAliases = {
  BiDetail: TbListDetails,
  BiExpandAlt: TbArrowsDiagonal,
  BsTranslate: TbLanguage,
  CiFileOn: TbFile,
  FaArchive: TbArchive,
  FaBeer: TbBeer,
  FaChartPie: TbChartPie,
  FaGraduationCap: TbSchool,
  FaImage: TbPhoto,
  FaMoneyBillWave: TbCash,
  FaPlay: TbPlayerPlayFilled,
  FaPrint: TbPrinter,
  FaRegEye: TbEye,
  FaRegEyeSlash: TbEyeOff,
  FaRegQuestionCircle: TbHelpCircle,
  FaRegTrashAlt: TbTrash,
  FaRegUserCircle: TbUserCircle,
  FaSortAlphaDown: TbSortAscendingLetters,
  FaSortAlphaUp: TbSortDescendingLetters,
  FaSortNumericDown: TbSortAscendingNumbers,
  FaSortNumericUp: TbSortDescendingNumbers,
  FaUniversity: TbBuildingBank,
  FaUserCheck: TbUserCheck,
  FaUserPlus: TbUserPlus,
  FaUsers: TbUsers,
  FaCheck: TbCheck,
  FaCode: TbCode,
  FaLock: TbLock,
  FaPersonChalkboard: TbPresentation,
  FaRegCopy: TbCopy,
  FaRotateRight: TbRotateClockwise,
  FaUserClock: FaUserClock,
  GiTwoCoins: TbCoins,
  GoArrowDownRight: TbArrowDownRight,
  GoArrowUpRight: TbArrowUpRight,
  GrUserAdmin: TbUserShield,
  HiLightningBolt: TbBolt,
  HiRefresh: TbRefresh,
  HiX: TbX,
  IoIosAddCircleOutline: TbCirclePlus,
  IoIosArrowBack: TbChevronLeft,
  IoIosArrowForward: TbChevronRight,
  IoIosAttach: TbPaperclip,
  IoIosCheckmarkCircle: TbCircleCheck,
  IoIosList: TbList,
  IoIosMail: TbMail,
  IoIosShareAlt: TbShare,
  IoMdLink: TbLink,
  IoMdSave: TbDeviceFloppy,
  IoMdSettings: TbSettings,
  IoMdThumbsDown: TbThumbDown,
  IoMdThumbsUp: TbThumbUp,
  IoAddCircleOutline: TbCirclePlus,
  IoAddOutline: TbPlus,
  IoMinusOutline: TbMinus,
  IoCall: TbPhoneFilled,
  IoChatbubbleEllipses: TbMessageDots,
  IoChevronDownOutline: TbChevronDown,
  IoChevronForward: TbChevronRight,
  IoClose: TbX,
  IoCloseOutline: TbX,
  IoCodeSlash: TbCode,
  IoDocumentTextSharp: TbFileText,
  IoEyeOffOutline: TbEyeOff,
  IoEyeOutline: TbEye,
  IoFilter: TbFilter,
  IoHome: TbHomeFilled,
  IoSearch: TbSearch,
  IoWarning: TbAlertTriangleFilled,
  IoWarningOutline: TbAlertTriangle,
  LiaNewspaper: TbNews,
  LuBookOpenText: TbBook,
  LuDownload: TbDownload,
  LuExternalLink: TbExternalLink,
  LuGraduationCap: TbSchool,
  LuInfo: TbInfoCircle,
  LuMenu: TbMenu2,
  LuReceipt: TbReceipt,
  LuSendHorizontal: TbSend,
  LuUpload: TbUpload,
  AlertTriangle: TbAlertTriangle,
  AlertOctagon: TbAlertOctagon,
  GripVertical: TbGripVertical,
  StickyNote: TbNote,
  Minus: TbMinus,
  Plus: TbPlus,
  MdAnnouncement: TbMessageReport,
  MdCardMembership: MdCardMembership,
  MdError: TbAlertCircleFilled,
  MdFilterList: TbFilter,
  MdLogout: TbLogout,
  MdOutlineCalendarToday: TbCalendar,
  MdOutlinePersonPin: TbUserPin,
  MdOutlineSpaceDashboard: TbLayoutDashboard,
  MdPreview: MdPreview,
  MdSpaceDashboard: TbLayoutDashboardFilled,
  MdThumbsUpDown: MdThumbsUpDown,
  PiChatSlashBold: TbMessageOff,
  PiExam: PiExam,
  PiGlobe: TbWorld,
  PiGlobeX: TbWorldOff,
  RxDotsHorizontal: TbDots,
  SlSettings: TbSettings,
  TbAlertCircle: TbAlertCircle,
  TbAppWindowFilled: TbAppWindowFilled,
  TbArrowBackUp: TbArrowBackUp,
  TbArrowForwardUp: TbArrowForwardUp,
  TbCheck: TbCheck,
  TbChevronDown: TbChevronDown,
  TbChevronUp: TbChevronUp,
  TbInfinity: TbInfinity,
  TbLayoutNavbar: TbLayoutNavbar,
  TbLock: TbLock,
  TbLockCog: TbLockCog,
  TbLockOpen: TbLockOpen,
  TbMaximize: TbMaximize,
  TbMessageChatbotFilled: TbMessageChatbotFilled,
  TbSitemap: TbSitemap,
  TbSum: TbSum,
  TbWorldSearch: TbWorldSearch,
  TbX: TbX,
  Analytics: Analytics,
  Bulb: Bulb,
  Chat: Chat,
  Dashboard: Dashboard,
  Edit: Edit,
  Face: Face,
  Faq: Faq,
  Language: Language,
  Layout: Layout,
  Members: Members,
  Pending: Pending,
  Receipt: Receipt,
  Sparkles: Sparkles,
  Store: Store,
  StoreActive: StoreActive,
  Studio: Studio,
  StudioActive: StudioActive,
  VerticalEllipsis: VerticalEllipsis,
  Window: Window,
  AmountUsage: AmountUsage,
  FilledAnalytics: FilledAnalytics,
  FilledBulb: FilledBulb,
  FilledChat: FilledChat,
  FilledEdit: FilledEdit,
  FilledFace: FilledFace,
  FilledFaq: FilledFaq,
  FilledLayout: FilledLayout,
  FilledMembers: FilledMembers,
  FilledAmountUsage: FilledAmountUsage,
};

const iconList = { ...registry, ...legacyAliases } satisfies Record<
  string,
  React.ComponentType<any>
>;

export const Icons = Object.entries(iconList).reduce(
  (acc, [key, value]) => {
    acc[key] = createIcon(value, key);
    return acc;
  },
  {} as Record<keyof typeof iconList, ReturnType<typeof createIcon>>
);
