import { Icons } from './_constants/iconList';

export type { CreatedIcon } from './_utils/createIcon';

// 각 아이콘을 개별적으로 export (Icons. 없이 직접 사용 가능)
export const {
  // BI Icons
  BiDetail,
  BiExpandAlt,
  // BS Icons
  BsTranslate,
  // CI Icons
  CiFileOn,
  // FA Icons
  FaArchive,
  FaBeer,
  FaChartPie,
  FaGraduationCap,
  FaImage,
  FaMoneyBillWave,
  FaPlay,
  FaPrint,
  FaRegEye,
  FaRegEyeSlash,
  FaRegQuestionCircle,
  FaRegTrashAlt,
  FaRegUserCircle,
  FaSortAlphaDown,
  FaSortAlphaUp,
  FaSortNumericDown,
  FaSortNumericUp,
  FaUniversity,
  FaUserCheck,
  FaUserPlus,
  FaUsers,
  // FA6 Icons
  FaCheck,
  FaCode,
  FaLock,
  FaPersonChalkboard,
  FaRegCopy,
  FaRotateRight,
  FaUserClock,
  // GI Icons
  GiTwoCoins,
  // GO Icons
  GoArrowDownRight,
  GoArrowUpRight,
  // GR Icons
  GrUserAdmin,
  // HI Icons
  HiLightningBolt,
  HiRefresh,
  HiX,
  // IO Icons
  IoIosAddCircleOutline,
  IoIosArrowBack,
  IoIosArrowForward,
  IoIosAttach,
  IoIosCheckmarkCircle,
  IoIosList,
  IoIosMail,
  IoIosShareAlt,
  IoMdLink,
  IoMdSave,
  IoMdSettings,
  IoMdThumbsDown,
  IoMdThumbsUp,
  // IO5 Icons
  IoAddCircleOutline,
  IoAddOutline,
  IoMinusOutline,
  IoCall,
  IoChatbubbleEllipses,
  IoChevronDownOutline,
  IoChevronForward,
  IoClose,
  IoCloseOutline,
  IoCodeSlash,
  IoDocumentTextSharp,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFilter,
  IoHome,
  IoSearch,
  IoWarning,
  IoWarningOutline,
  // LIA Icons
  LiaNewspaper,
  // LU Icons
  LuBookOpenText,
  LuDownload,
  LuExternalLink,
  LuGraduationCap,
  LuInfo,
  LuMenu,
  LuReceipt,
  LuSendHorizontal,
  LuUpload,
  // MD Icons
  MdAnnouncement,
  MdCardMembership,
  MdError,
  MdFilterList,
  MdLogout,
  MdOutlineCalendarToday,
  MdOutlinePersonPin,
  MdOutlineSpaceDashboard,
  MdPreview,
  MdSpaceDashboard,
  MdThumbsUpDown,
  // PI Icons
  PiChatSlashBold,
  PiExam,
  PiGlobe,
  PiGlobeX,
  // RX Icons
  RxDotsHorizontal,
  // SL Icons
  SlSettings,
  // TB Icons
  TbAlertCircle,
  TbAppWindowFilled,
  TbArrowBackUp,
  TbArrowForwardUp,
  TbCheck,
  TbChevronDown,
  TbChevronUp,
  TbInfinity,
  TbLayoutNavbar,
  TbLock,
  TbLockCog,
  TbLockOpen,
  TbMaximize,
  TbMessageChatbotFilled,
  TbSitemap,
  TbSum,
  TbWorldSearch,
  TbX,
  // Lucide icons surfaced under friendly names (Workflow chrome)
  AlertTriangle,
  AlertOctagon,
  GripVertical,
  StickyNote,
  Minus,
  Plus,
  // Custom SVG Icons
  Analytics,
  Bulb,
  Chat,
  Dashboard,
  Edit,
  Face,
  Faq,
  Language,
  Layout,
  Members,
  Pending,
  Receipt,
  Sparkles,
  Store,
  StoreActive,
  Studio,
  StudioActive,
  VerticalEllipsis,
  Window,
  AmountUsage,
  FilledAnalytics,
  FilledBulb,
  FilledChat,
  FilledEdit,
  FilledFace,
  FilledFaq,
  FilledLayout,
  FilledMembers,
  FilledAmountUsage,
} = Icons;

export default Icons;
