// Legacy Icon wrapper component for backward compatibility
export type { IconProps } from './Icon';
export { Icon } from './Icon';

// 모든 개별 아이콘 컴포넌트들 - Tree shaking 지원
export {
  Add,
  AmountUsage,
  // Custom SVG Icons
  Analytics,
  // Types
  type BaseIconProps,
  // React Icons - BI
  BiDetail,
  BiExpandAlt,
  // React Icons - BS
  BsTranslate,
  Bulb,
  Chat,
  // React Icons - CI
  CiFileOn,
  Close,
  Dashboard,
  Download,
  Edit,
  Error,
  // React Icons - FA
  FaArchive,
  FaBeer,
  Face,
  FaChartPie,
  // React Icons - FA6
  FaCheck,
  FaCode,
  FaGraduationCap,
  FaImage,
  FaLock,
  FaMoneyBillWave,
  FaPersonChalkboard,
  FaPlay,
  FaPrint,
  Faq,
  FaRegCopy,
  FaRegEye,
  FaRegEyeSlash,
  FaRegQuestionCircle,
  FaRegTrashAlt,
  FaRegUserCircle,
  FaRotateRight,
  FaSortAlphaDown,
  FaSortAlphaUp,
  FaSortNumericDown,
  FaSortNumericUp,
  FaUniversity,
  FaUserCheck,
  FaUserClock,
  FaUserPlus,
  FaUsers,
  FilledAmountUsage,
  FilledAnalytics,
  FilledBulb,
  FilledChat,
  FilledEdit,
  FilledFace,
  FilledFaq,
  FilledLayout,
  FilledMembers,
  // React Icons - GI
  GiTwoCoins,
  // React Icons - GO
  GoArrowDownRight,
  GoArrowUpRight,
  // React Icons - GR
  GrUserAdmin,
  // React Icons - HI
  HiLightningBolt,
  HiRefresh,
  HiX,
  // Common UI Icons (별칭들)
  Home,
  type IconType,
  IconTypes,
  Info,
  // React Icons - IO5
  IoAddCircleOutline,
  IoAddOutline,
  IoCall,
  IoChatbubbleEllipses,
  IoChevronDownOutline,
  IoChevronForward,
  IoClose,
  IoCloseOutline,
  IoCodeSlash,
  IoDocumentTextSharp,
  IoEyeOffOutline,
  IoEyeOutline,
  IoFilter,
  IoHome,
  // React Icons - IO
  IoIosAddCircleOutline,
  IoIosArrowBack,
  IoIosArrowForward,
  IoIosAttach,
  IoIosCheckmarkCircle,
  IoIosList,
  IoIosMail,
  IoIosShareAlt,
  IoMdLink,
  IoMdSave,
  IoMdSettings,
  IoMdThumbsDown,
  IoMdThumbsUp,
  IoSearch,
  IoWarning,
  IoWarningOutline,
  Language,
  Layout,
  // React Icons - LIA
  LiaNewspaper,
  // React Icons - LU
  LuBookOpenText,
  LuDownload,
  LuExternalLink,
  LuGraduationCap,
  LuInfo,
  LuMenu,
  LuReceipt,
  LuSendHorizontal,
  LuUpload,
  // React Icons - MD
  MdAnnouncement,
  MdCardMembership,
  MdError,
  MdFilterList,
  MdLogout,
  MdOutlineCalendarToday,
  MdOutlinePersonPin,
  MdOutlineSpaceDashboard,
  MdPreview,
  MdSpaceDashboard,
  MdThumbsUpDown,
  Members,
  MenuIcon,
  Pending,
  // React Icons - PI
  PiChatSlashBold,
  PiExam,
  PiGlobe,
  PiGlobeX,
  Receipt,
  Refresh,
  // React Icons - RX
  RxDotsHorizontal,
  Search,
  Settings,
  // React Icons - SL
  SlSettings,
  Sparkles,
  Store,
  StoreActive,
  Studio,
  StudioActive,
  // React Icons - TB
  TbAppWindowFilled,
  TbInfinity,
  TbLayoutNavbar,
  TbLockCog,
  TbMessageChatbotFilled,
  TbSum,
  TbWorldSearch,
  Upload,
  VerticalEllipsis,
  Warning,
  Window,
} from './Icons';
